name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Style
        run: |
          python ./tests/style.py

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip install sphinx sphinx-rtd-theme
      - name: Docs
        run: |
          make docs

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          make driver
          make kernels

      - uses: actions/upload-artifact@master
        with:
          name: build-files
          path: ./build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@master
        with:
          name: build-files
          path: ./build

      - name: Install
        run: |
          pip install -r requirements.txt
          make install

      - name: Test video
        run: |
          cd ./tests
          pianoray -p ../build/kernels -o a.mp4 ./test.py:Pipeline

      - name: JUnit
        run: |
          make test
