name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Style
        run: |
          python ./tests/style.py

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip install sphinx sphinx-rtd-theme
      - name: Docs
        run: |
          make docs

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Build and install
        run: |
          make driver
          make kernels
          make install

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: See what this does
        run: |
          ls
          ls ./build
      - name: Test video
        run: |
          cd ./tests
          pianoray -p ../build/kernels -o a.mp4 ./test.py:Pipeline
      - name: JUnit
        run: |
          make test
